---
- name: Actualizar sistema operativo Red Hat/CentOS
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Actualizar sistema operativo SUSE
  zypper:
    name: '*'
    state: latest
  when: ansible_os_family == 'Suse'

- name: Actualizar sistema operativo Debian/Ubuntu
  apt:
    name: '*'
    state: latest
    update_cache: yes
    force_apt_get: yes
  when: ansible_os_family == 'Debian'

- name: Reiniciar para aplicar los cambios
  reboot:
    reboot_timeout: 300

- name: Remover kernels antiguos sin uso en Red Hat/CentOS
  shell: |
    package-cleanup --oldkernels --count=1 -y
  when:
    ansible_os_family == 'RedHat' and
    os_release.split('.')[0] == '7'

- name: Remover archivo persistent-net.rules
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  shell: |
        rm -rfv /etc/udev/rules.d/[1-9][0-9]-persistent-net.rules
