---
- name: Crear maquina virtual
  vmware_guest:
    annotation:           "{{ vm_annotation }}"
    hostname:             "{{ vmware_host }}"
    username:             "{{ vmware_user }}"
    password:             "{{ vmware_password }}"
    datacenter:           "{{ vsphere_datacenter }}"
    cluster:              "{{ vm_cluster }}"
    resource_pool:        "{{ vm_resourcepool }}"
    validate_certs:       no
    wait_for_ip_address:  yes
    name:                 "{{ vm_name }}"
    force:                yes
    folder:               "{{ vm_folder }}"
    guest_id:             "{{ vm_ostype }}"
    state:                "{{ vm_state }}"
    template:             "{{ vm_template }}"
    datastore:            "{{ vm_datastore }}"
    hardware:
      memory_mb:          "{{ vm_memory*1024 }}"
      num_cpus:           "{{ vm_cpus }}"
      scsi:               "{{ vm_disktype }}"
      hotadd_cpu:         True
      hotadd_memory:      True
    networks:             "{{ vm_networks }}"
    disk:                 "{{ vm_disks }}"
    customization:
      password:           "{{ os_adminpass }}"
      hostname:           "{{ os_hostname }}"
      domain:             "{{ os_domain | default(omit) }}"
      dns_servers:        "{{ os_dns.split(',') }}"
      timezone:           "{{ os_timezone }}"