---
- name: Ajustes personalizados post despliegue de maquina virtual en Windows
  include_tasks: windows-customization.yml
  when: ansible_system == 'Win32NT'

- name: Ajustes personalizados post despliegue de maquina virtual en Linux
  include_tasks: linux-customization.yml
  when: ansible_system == 'Linux'