---
- name: Consultar fichero systemd de vault
  register: vault_systemd_file
  stat:
    path: /etc/systemd/system/vault.service

- name: Consultar fichero SysV de vault
  register: vault_sysv_file
  stat:
    path: /etc/init.d/vault

- name: Detener vault
  when: vault_systemd_file.stat.exists or vault_sysv_file.stat.exists
  service:
    name: vault
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Borrar archivos de vault
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ vault_config_dir }}"
    - "{{ vault_data_dir }}"
    - "{{ vault_audit_dir }}"
    - "{{ vault_runtime_dir }}"
    - "{{ vault_bin_dir }}/vault"
    - "{{ vault_home_dir }}"
    - /tmp/{{ vault_url | basename }}
    - /etc/systemd/system/vault.service
    - /etc/tmpfiles.d/vault.conf

- name: Borrar usuario de vault
  user:
    name: "{{ vault_user }}"
    state: absent

- name: Borrar grupo de vault
  group:
    name: "{{ vault_group }}"
    state: absent
