---
# tasks file for ansible-role-consul-setup
- name: Verificar instalacion existente de consul
  command: which consul
  register: consul_command
  failed_when: consul_command.rc not in [0,1]
  environment:
    PATH: "{{ consul_bin_dir }}:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

- name: Crear grupo para consul
  group:
    name: "{{ consul_group }}"
    system: yes

- name: Crear usuario para consul
  user:
    name: "{{ consul_user }}"
    system: yes
    group: "{{ consul_group }}"
    create_home: no
    home: "{{ consul_home_dir }}"
    shell: "{{ consul_shell }}"

- name: Crear directorio $HOME de consul
  file:
    state: directory
    path: "{{ consul_home_dir }}"
    mode: 0750
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: Crear directorios de trabajo de consul
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0750
    recurse: yes
  with_items:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_runtime_dir }}"

- name: Crear directorios de binario de consul
  file:
    state: directory
    path: "{{ consul_bin_dir }}"
    owner: root
    group: root
    mode: 0755

- name: Descargar consul
  when: consul_command.rc != 0
  get_url:
    url: "{{ consul_url }}"
    dest: /tmp/{{ consul_url | basename }}
    mode: 0644
  register: consul_download

- name: Descomprimir consul
  unarchive:
    src: /tmp/{{ consul_url | basename }}
    remote_src: yes
    dest: "{{ consul_bin_dir }}"
    mode: 0755
    owner: root
    group: root
  when: consul_download.changed

- name: Eliminar zip de consul
  file:
    state: absent
    path: /tmp/{{ consul_url | basename }}
  when: consul_download.changed

- name: Crear configuracion tmpfiles.d de consul
  template:
    src: templates/tmpfiles.conf.j2
    dest: /etc/tmpfiles.d/consul.conf
  register: tmpfiles_conf

- name: Aplicar cambios tmpfiles.d de consul
  command: systemd-tmpfiles --create
  when: tmpfiles_conf.changed

- name: Habilitar autocompletado consul
  command: consul -autocomplete-install
  register: consul_autocomplete
  failed_when: consul_autocomplete.rc not in [0,1]
  environment:
    PATH: "{{ consul_bin_dir }}:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

- name: Crear configuracion de servicio consul
  template:
    src: templates/consul.service.j2
    dest: /etc/systemd/system/consul.service
    mode: 0644
    owner: root
    group: root
  register: consul_service

- name: Recargar systemd    
  command: systemctl daemon-reload
  when: consul_service.changed
