---
- name: Gather necessary facts
  setup:
    gather_subset: min
  when: ansible_system is not defined

- name: Check pre-requisites
  include_tasks: prechecks.yml
  when: role_action == 'install'

- name: Perform installation of packages
  include_tasks: install.yml
  when: role_action == 'install'

- name: Set listen_addr variable
  set_fact:
    listen_addr: "{{ ansible_env.SSH_CONNECTION.split(' ')[2] }}"
  when: role_action in ["init","join"]

- name: Initialize Swarm
  include_tasks: swarm-init.yml
  when: role_action == 'init'

- name: Join nodes to the Swarm
  include_tasks: swarm-join.yml
  when: role_action == 'join'
