---
- name: Instalar dependencias (solo basados en RedHat)
  yum:
    name: "{{ os_packages.redhat }}"
    state: present
  when: os_version in ["rhel7","rhel8","centos7","centos8","amazon2"]

- name: Deshabilitar SELinux (solo basados en RedHat)
  selinux:
    state: disabled
  when: os_version in ["rhel7","rhel8","centos7","centos8","amazon2"]

- name: Habilitar Firewall (solo basados en RedHat)
  service:
    name: firewalld
    state: "{{ 'started' if consul_firewall_ports is defined and vault_firewall_ports is defined else 'stopped' }}"
    enabled: "{{ 'yes' if consul_firewall_ports is defined and vault_firewall_ports is defined else 'no' }}"
  when: os_version in ["rhel7","rhel8","centos7","centos8","amazon2"]

- name: Configurar hostname
  hostname:
    name: "{{ consul_nodename if consul_nodename is defined else vault_nodename }}"

- name: Configurar archivo hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Configurar PasswordAuthentication de SSH para red local
  when: vpc_match_host is defined
  register: sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Host {{ vpc_match_host }}
        PasswordAuthentication yes
    marker: "# {mark} PermitBastionPasswordAuth block"

- name: Reiniciar servicio SSH para aplicar los cambios
  when: sshd_config.changed
  service:
    name: sshd
    state: restarted

- name: Crear usuario para administracion del SO
  when:
    - os_admin_user is defined
    - os_admin_password is defined
  register: os_admin_creation
  user:

    name: "{{ os_admin_user }}"
    password: "{{ os_admin_password | password_hash('sha512') }}"
    state: present
    comment: "Orion Admin"
    shell: /bin/bash
    update_password: on_create

- name: Brindar permisos de sudo al usuario administrador de SO
  when: os_admin_creation.changed
  template:
    dest: /etc/sudoers.d/orion
    src: templates/sudoers.j2
    mode: 0640
    owner: root
    group: root
    validate: '/usr/sbin/visudo -cf %s'

