---
- name: Instalar software esencial en Amazon
  yum:
    name: "{{ linux_amazon_packages }}"
    state: present

- name: Remover software innecesario
  yum:
    name: libvirt-daemon
    state: absent