---
- name: Habilitar Escritorio Remoto
  win_shell: Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0

- name: Instalacion de Windows Managemt Framework (WMF) 5.1 en Windows 2012
  when:
    os_release is defined and
    os_release == '2012r2'
  block:
    - name: Descargar programas localmente
      shell: |
        smbclient {{ smbinst_share }} -U '{{ smbinst_domain }}\{{ smbinst_user }}'%'{{ smbinst_pass }}' \
          -c "recurse ; prompt off ; cd {{ path_wmf51forwin8 | dirname }} ; get {{ path_wmf51forwin8 | basename }}"
      vars:
        ansible_connection: local
        
    - name: Copiar instalador de WMF 5.1
      win_copy:
        src: "{{ path_wmf51forwin8 | basename }}"
        dest: C:\Windows\temp\

    - name: Instalar WMF 5.1
      win_hotfix:
        source: C:\Windows\temp\{{ path_wmf51forwin8 | basename }}
        state: present
      register: wmf_installation

    - name: Borrar archivos de instalacion usados remotamente
      win_file:
        path: C:\Windows\temp\{{ path_wmf51forwin8 | basename }}
        state: absent

    - name: Borrar archivos de instalacion usados localmente
      shell: rm -f {{ path_wmf51forwin8 | basename }} 
      vars:
        ansible_connection: local

    - name: Reiniciar para aplicar cambios pendientes
      win_reboot:
        reboot_timeout: 600
      when:
        (wmf_installation is defined and
        wmf_installation.changed)
