---
- name: Enviar por correo la clave de administrador
  mail:
    host: "{{ smtp_server }}"
    port: 25
    from: "{{ mail_from }}"
    to: "{{ mail_to }}"
    subject: "{{ mail_subject }}"
    body: "{{ mail_body }}"
    attach:
      - "{{ tmpjob }}/credenciales.zip"
  run_once: yes

- name: Remover archivos y roles temporales
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ tmpjob }}"
    - group_vars/{{ tmpjob }}
